runziggurat/xrpl

SPEC.md
The spec doesn't contain any specific test cases yet, these will be documented as we map out the protocol.
=> Doc: initial draft of test specification

src/protocol/mod.rs, src/protocol/writing.rs
Implements `Writing` for the `SyntheticNode`.
=> Implement writing protocol

src/protocol/codecs/binary.rs
Message type 15 that was received in tests.
=> feat: add `Endpoints` message type

src/protocol/handshake.rs, src/protocol/reading.rs, src/protocol/writing.rs, src/tests/conformance/handshake.rs, src/tools/constants.rs, src/tools/inner_node.rs, src/tools/mod.rs, src/tools/synth_node.rs
1. Extract InnerNode
2. Add channels for InnerNode -> SyntheticNode messages
3. Basic setup for tests
=> Rename SyntheticNode to InnerNode, wrap it in a new SyntheticNode that has an inbound message queue

SPEC.md, src/protocol/codecs/binary.rs, src/protocol/handshake.rs, src/setup/config.rs
Add GetObjectByHash message and payload. Config setup for transaction reduce relay.
=> Feature: add GetObjectByHash message type

src/tools/rpc.rs
Created a convenience function in `rpc` module to be used by various `get_*_info` functions.
=> Refactor: Extract common code in rpc module.

src/setup/config.rs, src/setup/node.rs, src/setup/testnet/mod.rs, src/tests/conformance/cmd/squelch.rs, src/tests/conformance/handshake.rs, src/tests/conformance/mod.rs, src/tests/conformance/query/get_by_hash.rs, src/tests/conformance/stateful.rs, src/tests/conformance/status.rs
- also: the RPC port is moved to const
=> chore: add log_to_stdout to node builder

SPEC.md, src/tests/conformance/cmd/mod.rs, src/tests/conformance/cmd/validators.rs, src/tests/conformance/mod.rs, src/tests/conformance/query/peer_shard_info.rs
1. Moved key constants to higher level module.
2. Test for a valid TmValidatorListCollection message.
=> Feature: Add a check for TmValidatorListCollection message.

SPEC.md, src/tests/conformance/cmd/squelch.rs
- Also: Test index symbolic language legend update.
=> doc: Update squelching description in the SPEC doc

SPEC.md, src/protocol/codecs/binary.rs, src/protocol/handshake.rs, src/setup/config.rs, src/tests/conformance/query/mod.rs, src/tests/conformance/query/replay_delta.rs
1. Add required variants for Payload enum.
2. Add test for mtREPLAY_DELTA_RESPONSE message.
=> Feature: Add mtREPLAY_DELTA_RESPONSE message test.

SPEC.md, src/protocol/codecs/binary.rs, src/setup/config.rs, src/setup/node.rs, src/tests/conformance/query/peer_shard_info.rs
1. Add TmPeerShardInfoV2 payload
2. Add optional history sharding
3. Add TmGetPeerShardInfoV2 message test
=> Feat/test for peer_shard_info_v2 message

SPEC.md, src/protocol/codecs/binary.rs, src/setup/config.rs, src/setup/constants.rs, src/setup/node.rs, src/tests/conformance/cmd/cluster.rs, src/tests/conformance/cmd/mod.rs, src/tests/conformance/mod.rs, src/tools/config.rs, src/tools/inner_node.rs
* Add TmCluster message type
* Add option to use predefined keys in handshake
* Enable clustering in rippled
* Add test for TmCluster
=> Feature: Add test for TmCluster

src/protocol/codecs/binary.rs
- Add TmValidatorList message type
=> feat: add TmValidatorList message type

SPEC.md, src/protocol/handshake.rs, src/tests/resistance/handshake.rs, src/tools/config.rs, src/tools/inner_node.rs
* Add option to introduce errors to a handshake
* Add test for bit flips during a handshake
=> Feature: Test bit flips during handshake

src/protocol/handshake.rs, src/tests/resistance/handshake.rs, src/tools/inner_node.rs
* Use wait_until! for faster test progress
* Extract handshake resistance config to a struct
=> Refactor: Resistance handshake tests refactored

src/tests/resistance/handshake.rs
Rippled seems to treat peers at the same IP somewhat strange: this test usually passed, but failed occasionally. Fixing IPs to be different seems to do the trick.
=> Chore: Configure SynthNode to use different ips

SPEC.md, src/tests/resistance/random_bytes.rs
- Add random bytes test pre-handshake
- replace sleep with `wait_until!`
=> feat: add random bytes test pre-handshake

SPEC.md, src/tests/performance/get_trans.rs, src/tests/performance/mod.rs
Performance test that is done by getting transaction details (using transaction hash) from the node.
=> feat: getting transaction details performance test

src/protocol/codecs/message.rs, src/setup/node.rs, src/tests/performance/connections.rs, src/tests/performance/get_trans.rs, src/tests/performance/ping_pong.rs, src/tools/metrics/recorder.rs
Refactoring changes to incorporate many review fixes and keep perf tests consistent across the projects.
Commits will be squashed to single one in this PR.
=> refactor: backport changes to perf tests

CRAWLER.md, Cargo.toml, src/tools/crawler/args.rs, src/tools/crawler/main.rs
Very humble beginning for the crawler.
=> feature: Add crawler

src/protocol/reading.rs, src/tools/crawler/args.rs, src/tools/crawler/crawler.rs, src/tools/crawler/main.rs, src/tools/crawler/network.rs
Initial idea for network crawling.
=> feat: add basic network crawling

CRAWLER.md, Cargo.toml, src/tools/crawler/args.rs, src/tools/crawler/crawler.rs, src/tools/crawler/main.rs, src/tools/crawler/metrics.rs, src/tools/crawler/network.rs, src/tools/crawler/rpc.rs
Performs a handshake with a new node. Collects statistics about successes.
=> feat: add handshake attempt to crawler

src/tools/crawler/crawler.rs, src/tools/crawler/network.rs
* Increase retry delay after failure
* Make crawler update stats in a loop
* Reset connection failure count when successfully connected
=> feat: make crawler to update its stats in a loop

src/tools/crawler/crawler.rs
- uniformly spread the peerlist requests in the time domain
- also increase request frequency
=> chore(crawler): randomize time periods for requests

Cargo.toml, src/tools/crawler/main.rs, src/tools/crawler/metrics.rs, src/tools/crawler/network.rs, src/tools/crawler/rpc.rs
* Use NetworkSummary from ziggurat-core package
=> refactor: use ziggurat-core for crawler

src/protocol/handshake.rs, src/tools/crawler/crawler.rs, src/tools/crawler/network.rs, src/tools/crawler/rpc.rs
* reduce logging
* check for handshake in background task
* make crawler rpc output optional
=> chore: crawler improvements

README.md
=> doc: add note about legacy openssl functions

src/setup/node.rs
**`wait_until_exit` API**
A non-blocking function which periodically checks the node's status code.
**Bonus info:**
Once the async `Drop` trait support is introduced in Rust, we can remove the loop and use a non-blocking `tokio::process::Command` and then call a tokio version of `wait()` function on it.
Because, calling `wait()` on `std::process::Command` will block the
entire tokio runtime and the whole test process will be stopped until
the node is actually killed - which is bad if we have other
tokio threads running.
So looping with a non-blocking `try_wait()` is the alternative solution.
=> feat(node): introduce wait_until_exit API

README.md, src/setup/testnet/mod.rs, tools/account_info.py, tools/setup_env.sh
_Introduces a convenience shell script for setting up the work environment._
- The script performs the following:
- Sets up `~/.ziggurat/ripple` directories
- Creates a default config file
- ~~Adds IP addresses used in performance tests~~
- Sets up an initial node state
- Documentation changes are included.
=> Introduce setup script

.github/workflows/rippled.yml
- Integrates the new `setup_env.sh` script into the workflow
- Renames `Github Actions Bot -> github-actions[bot]`
=> ref(ci): use setup script

src/tests/idle_node_in_the_background.rs
The synthetic node should automatically reply to ping messages in order to keep the connection alive.
=> feat(dev): add ping-pong mechanism dev tests

.github/workflows/build-rippled.yml, .github/workflows/crawler.yml, .github/workflows/rippled.yml
- Refactors `install-* -> build-*`.
- Call `process-results` workflow from crawler
- Call `diff-with-previous` workflow from `rippled`
=> chore: call new workflows

src/tests/performance/connections.rs
trivial, discovered by Karlo in previous PR.  🙏
=> chore: remove commented out line

.github/workflows/rippled.yml
Workflow now complies with the new install instructions
=> chore: new ips script
