- .gitignore
- README.md
- src/tools/constants.rs
- Slower machines (Mac M2, e.g.) require a longer time for node setup.
- Small doc updates.
> fix: update conn timeouts

- src/tests/conformance/handshake.rs
- src/tests/conformance/query/peer_shard_info.rs
- src/tests/conformance/query/ping_pong.rs
- src/tools/inner_node.rs
- src/tools/synth_node.rs
One slight tracing improvement.
I'm thinking of adding one extra trace in the unicast function in the Synth_node implementation,
to print out the message which we are sending on the other side.
Since the below log is not very informative (without this change):
```
2022-09-21T08:55:45.503758Z TRACE tokio_util::codec::framed_impl: writing; remaining=40
2022-09-21T08:55:45.503775Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2022-09-21T08:55:45.503787Z TRACE node{name="0"}: pea2pea::protocols::writing: sent 40B to 127.0.0.1:8080
```
With the change, we get this output:
```
2022-09-21T08:55:45.503675Z TRACE node{name="0"}: ziggurat_xrpl::tools::synth_node: unicast send TmHaveTransactions(TmHaveTransactions { hashes: [[186, 166, 68, 138, 23, 250, 189, 4, 79, 210, 28, 63, 89
, …
```
> feat: improve unicast tracing

- SPEC.md
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/query/get_by_hash.rs
- src/tests/conformance/query/ledger.rs
- src/tests/conformance/query/peer_shard_info.rs
- src/tests/conformance/query/ping_pong.rs
- src/tools/constants.rs
- Tests are grouped into the following categories: conformance, performance, and resistance. Each test is named after the category it belongs to, in addition to what's being tested. For example, `c001_handshake_when_node_receives_connection` is the first conformance test and tests the handshake behaviour on the receiving end. The full naming convention is: `id_part_t(subtest_no)_(message type)_(extra_test_desc)`.
- SPEC.md updated accordingly
> refactor: adhere to new test naming convention

- src/setup/node.rs
`SocketAddr` is `Copy` so the value doesn't need to be moved.
> ref: remove unnecessary `move` for `Copy` type

- src/tests/conformance/query/get_by_hash.rs
Let's ensure all tests at the end of the test perform the shutdown on synth nodes.
> chore: always shutdown synth nodes

- SPEC.md
- src/protocol/codecs/binary.rs
- src/tests/conformance/mod.rs
- src/tests/conformance/squelch.rs
Here are the most important bits from the logs:
```
2022-09-26T20:56:40.950339Z DEBUG node{name="0"}: ziggurat_xrpl::protocol::reading: sending the message to the node's inbound queue
2022-09-26T20:56:40.950504Z TRACE node{name="0"}: ziggurat_xrpl::tools::synth_node: unicast send msg to 127.0.0.1:8080: TmSquelch(TmSquelch { squelch: true, validator_pub_key: [2, 244, 117, 76, 27, 51,
199, 211, 46, 128, 94, 178, 177, 135, 0, 154, 155, 67, 18, 68, 30, 145, 152, 131, 76, 91, 155, 99, 110, 45, 149, 84, 185], squelch_duration: Some(360) })
2022-09-26T20:56:40.950772Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2022-Sep-26 20:56:40.950794 UTC Peer:DBG [007] Connect 34.221.145.175:51235
2022-09-26T20:56:40.950804Z TRACE tokio_util::codec::framed_impl: writing; remaining=46 …
```
> feat: add c009 test for the mtSQUELCH message

- SPEC.md
- src/tests/conformance/query/peer_shard_info.rs
Some tests to check for basic relaying of TmGetPeerShardInfoV2 message:
1. Relay if everything is ok (correct key type and valid relays count.
2. Don't relay invalid key type.
3. Don't relay invalid relays count.
> Feature: Add relay check for TmGetPeerShardInfo

- src/setup/config.rs
- src/setup/constants.rs
- src/setup/mod.rs
- src/setup/node.rs
- src/setup/testnet/mod.rs
- src/tests/conformance/handshake.rs
- src/tools/constants.rs
- Constants belonging to the setup directory structure should be placed in setup/constants.rs
- Constants belonging to tools and tests directory structures should be placed in tools/constants.rs
> chore: centralize setup constants

- src/setup/node.rs
- src/tests/conformance/query/peer_shard_info.rs
- For some reason, stateful nodes 'node1' and 'node2' cannot reach a 'proposing.' server_state on Linux. Only 'node0' is capable of reaching the 'proposing.' state. That strange behaviour should be investigated further.
> chore: always serve the first stateful node first

- SPEC.md
- src/setup/node.rs
- src/tests/conformance/cmd/squelch.rs
- Ensure squelching works correctly in a multi-node network environment. A synthetic node should be able to squelch distant validators.
- SPEC.md updated accordingly
> feat: add c016 for the mtSQUELCH message

- SPEC.md
- src/tests/conformance/cmd/manifest.rs
- src/tests/conformance/cmd/mod.rs
Two checks for TmManifests messages:
1. Node sends TmManifests after handshake.
2. Node does not set TmManifests if there was no handshake.
> Feature: Add check for TmManifests messages.

- SPEC.md
- src/tests/conformance/cmd/endpoints.rs
- src/tests/conformance/cmd/mod.rs
Check for:
1. A node sends TmEndpoints after the handshake.
2. A node does not send TmEndpoints without the handshake.
> Feature: Add check for TmEndpoints messages.

- src/tests/conformance/cmd/squelch.rs
The c016 test was failing occasionally. Increasing the timeout seems to help.
> Chore: Increase timeout for TM_SQUELCH message

- SPEC.md
- src/setup/constants.rs
- src/setup/testnet/mod.rs
- src/tests/conformance/cmd/mod.rs
- src/tests/conformance/cmd/transaction.rs
- src/tests/conformance/query/get_by_hash.rs
- src/tests/conformance/stateful.rs
- src/tools/rpc.rs
1. Add timeout to `wait_for_account_data` function.
2. Add `submit_transaction` RPC call.
3. Add `mtTRANSACTION` relay test.
> Feature: test for mt transaction message

- src/tests/conformance/cmd/transaction.rs
- src/tests/conformance/query/get_by_hash.rs
- src/tests/conformance/stateful.rs
- src/tools/constants.rs
This commit makes constants for two accounts' hashes that are often used in tests.
> Chore: Make accounts' hashes into constants

- SPEC.md
- src/protocol/handshake.rs
- src/tests/mod.rs
- src/tests/resistance/handshake.rs
- src/tests/resistance/mod.rs
- src/tools/config.rs
- src/tools/inner_node.rs
- src/tools/synth_node.rs
* Add option to set custom 'User-Agent' header for a handshake
* Add test for large User-Agent header used in a handshake
> Feature: test for User-agent header being too long

- SPEC.md
- src/protocol/handshake.rs
- src/tests/resistance/handshake.rs
- src/tools/config.rs
- src/tools/inner_node.rs
* Chore: Rename `user_agent` config field to `ident`
* Feature: Add test for large 'Server' header during handshake.
> Feature: Test server identification too long

- SPEC.md
- src/tests/conformance/post_handshake/validators.rs
This PR covers the second part of the c026.  It performs the actual verification that a correctly-formed `TmValidatorList` message was received by `rippled`.
- creates two synth nodes
- sends our TmValidatorList message from node 1, and then node 2 listens for incoming TmValidatorListCollection messages
- filters the messages, looking for one with a single validator (the other two received have about 12 each).
- when it finds our message, does asserts on the random sequence value and master public key.  
- If no valid message is found after 5 seconds -- e.g., if I didn't send the original list message, or if I sent an invalid message -- then the test would fail.  This test only confirms a positive result.
> test: c026 for TmValidatorList, part 2

- tools/ips.py
Tool that generate dummy devices, set them hardware addresses, ip addresses and set link up. Along with that it generates Rust file with all valid IP addresses that has been added to devices.
Script currently works on Linux only and needs to be run with sudo (as there are needed privilages to create devices).
Dummy kernel module needed (should be present on every distro with default kernel).
> tests: added tool for generating dummy devices and Rust array with ips

- src/tests/performance/ping_pong.rs
- src/tools/ips.rs
- src/tools/mod.rs
This PR gives ability for performance ping test to use different IP addresses.
Currently it's recommended to generate addresses to cover all iterations of all tests, so it would be good to generate whole 24bit subnet. When pea2pea will allow to set REUSE_ADDR option "the hack" can be removed.
> refactor: ping performance test can use different source IPs

- src/tools/crawler/crawler.rs
- src/tools/crawler/network.rs
* Small improvement: keep track of which nodes are already connected and don't connect again
* Add connection time to node's stats.
> feat: crawler connected stats

- Cargo.toml
- src/tools/crawler/crawl.rs
- src/tools/crawler/crawler.rs
- src/tools/crawler/main.rs
- src/tools/crawler/network.rs
Crawler using /crawl endpoint to find other peers. More information at https://xrpl.org/peer-crawler.html
> feat: use /crawl endpoint for crawling ripple network

- src/tools/crawler/crawler.rs
- src/tools/crawler/network.rs
Try to connect in a loop. If failed to connect wait for 10 seconds and try again. Maximum number of tries set to 255.
> feat: add connection retry if failed

- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
Presents basic stats (number of nodes and connections) via rpc.
> feat: add presenting basic crawler stats

- CRAWLER.md
- src/tools/crawler/rpc.rs
Adds option to dump crawler's stats to a file.
At this point there are no safety guards to protect against directory traversal.
> feat: add option to dump crawler's stats to a file

- Cargo.toml
- src/tests/conformance/post_handshake/validators.rs
- src/tests/conformance/query/peer_shard_info.rs
plus an extra commit now that I touched these files:
[chore(tests): apply ziggurat-core ERR messages](https://github.com/runziggurat/xrpl/commit/08807e9db5502f98a185df3d8e7e35b718af71a7)
Also: [chore: run cargo sort](https://github.com/runziggurat/xrpl/pull/113/commits/08070f5e5544322e09a8ddd07df8ba824416c047)
> chore(tests): set log_to_stdout to false in all tests 

- src/tools/crawler/crawl.rs
- src/tools/crawler/crawler.rs
- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
Necessary changes to allow for crawling multiple ports:
- the port number returned from the `/crawl` response
- `/crawl` default port (51235) as per https://xrpl.org/peer-crawler.html
- 2459 IANA assigned port as per https://xrpl.org/peer-protocol.html
> feat: crawl multiple ports

- src/setup/config.rs
- src/setup/node.rs
- src/tests/resistance/handshake.rs
```
fix: detect connection using num_connected function
- when the node initiates the connection,
we cannot assume correctly fwhich IP the node will
use to create a network socket. Therefore, we shouldn't
use `is_connected` function in this test
```
```
chore: allow extra debug traces
Enable extra debug traces from the node when the log_to_stdout option is
used.
```
> r001_t2 Mac fix: detect connection using num_connected function

- src/tests/idle_node_in_the_background.rs
- adds development tests used for some extra side-testing.
- these are used when synth nodes are run as a separate binary (PR will be delivered later for this functionality)
- every test runs a node forever with a slight variation:
- `dev001_t1_RUN_NODE_FOREVER_with_logs`
- `dev001_t2_RUN_NODE_FOREVER_no_logs`
- `dev002_t1_MONITOR_NODE_FOREVER_WITH_SYNTH_NODE_sn_is_conn_initiator`
- `dev002_t2_MONITOR_NODE_FOREVER_WITH_SYNTH_NODE_sn_is_conn_responder`
- also (!): these tests are not yet included in the mod tree! these still do not compile by default - and cannot be compiled yet.
here's a list of things that will be delivered later to make these tests work:
- include `chrono` crate in the `Cargo.toml`
- pull out and separate the `crawl` module from the `crawler` binary
- add a new …
> feat(tests): add a dev test suite

- Cargo.toml
- src/tools/crawler/metrics.rs
Exactly the same as with zcash, I've updated the xrpl crawler to use:
• new spectre API to fetch indices
• remove AGraph as struct, using updated NetworkSummary
> feat: update crawler to use latest NetworkSummary & spectre

- src/tools/crawler/crawl.rs
- src/tools/crawler/crawler.rs
- formatted printout with compressed info so it doesn't clutter the output with many newlines
- removed `(super)` from `pub(super)` because the `crawl` mod will be taken out and used by other tests from this binary (source code tree)
example of the printout:
```
server: build_version: 1.9.4, server_state: connected, server_uptime: 36
peerlist:
[00034]: 100.24.12.73:51235                     AyT/MLgoFGxwXrV8t0WVxZFQw8LgV4ypYXn8rp5ewGzd
[out]:                          version: rippled-1.9.4                  shards: None ledgers: Some("77995485-78015485")
[00034]: 13.48.204.149:51235                    ArO1nS71bRFvZPx3qWtev20+k3D5B4Aji9k68Wgprjyu
[out]:                          version: rippled-1.9.4                  shards: None ledgers: Some("77995485-78015485")
[00034]: 13.49.231.59:51235 …
```
> feat(crawler): add Display trait

- .github/workflows/rippled.yml
- .github/workflows/test-suite.yml
Integrates a new workflow for building and running a `rippled` instance through the test suite and logging the results daily under `results/rippled`.
~~**Note:**
The setup of the initial node state is currently relying on a long wait period (5m) before attempting to run `tools/transfer.py`. This behavior is of course not ideal and should be the subject of a future PR.~~
> feat: rippled ci

- src/protocol/handshake.rs
- src/tests/conformance/cmd/cluster.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/mod.rs
- src/tests/conformance/query/ledger.rs
- src/tests/conformance/query/ping_pong.rs
- src/tests/idle_node_in_the_background.rs
- src/tests/performance/connections.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/handshake.rs
- src/tests/resistance/random_bytes.rs
- src/tools/config.rs
- src/tools/inner_node.rs
- src/tools/synth_node.rs
TestConfig used to be an input for some conformance tests and also for a SyntheticNode creation. Now, it's decoupled:
- SyntNodeCfg ---> creation of the SyntheticNode
- TestConfig ---> used only for a test configuration (in conformance)
Also - the Handshake config has been moved to src/protocol/ and is used in both InnerNode and SyntNodeCfg.
Duplicated InnerNodeCfg handshake elements have been removed.
> refactor(synth_node): more flexible handshake cfg

- .github/workflows/crawler.yml
This PR introduces a new workflow that will:
1. Compile a `rippled` node from source
2. Crawl the network, using the built node as the entry point
3. Produce network metrics under the `results/crawler` directory.
> feat: crawler workflow

- SPEC.md
- src/tests/conformance/query/ping_pong.rs
- src/tools/synth_node.rs
More tests asserting ping/pong messages flow.
The node sends first ping after about 60 seconds and expects response within the same time. If no valid response came then the peer gets disconnected.
> feature: more ping/pong conformance tests

- .github/workflows/rippled.yml
Included with this PR:
- A new step that will display the output of the `diff` command between the workflows latest run (`latest.jsonl`) and the one prior to that (`comparison.jsonl`)
- The json files are modified in a new function, `filter_json`, to filter out things that would clog the output of `diff`, e.g `exec_time` and `type`.
> feat(ci): display diff from last run

- .github/workflows/crawler.yml
- .github/workflows/install-rippled.yml
- .github/workflows/rippled.yml
This PR:
- Moves shared `install-rippled` code into a new workflow.
- Adjusts the rippled workflow to call the `process-results` workflow under `runziggurat/zcash`.
> Reuse workflows

- synth_node_bin/Cargo.toml
- synth_node_bin/src/main.rs
A synthetic node binary can be used to interact with the node in the background from a different runtime environment.
> feat: add synth_node_bin files

- README.md
Improvement Bucket Task: `Add deps.rs badges to all our readme documents`
> docs: add deps.rs badge to readme

- README.md
extension of the Improvement Bucket Task: `Add deps.rs badges to all our readme documents`
- added workflow CI badge
- moved badges below title
> chore: add workflow badge, move both badges below title

- .github/workflows/crawler.yml
- .github/workflows/rippled.yml
Call the new shared workflows under the `ziggurat-core` repo.
> ref: call workflows under `ziggurat-core`

- README.md
The sample invocations were changed in the ips.py script, but not here.
> docs: update readme to reflect new destination file for ips.py

- PERF.md
- README.md
Last of a series of PRs related to these three improvement bucket list items
- How to share common scripts across different repos
- Think how to avoid having modified file in the repo after running the script
- Move the ips.py script to some common place for scripts in ziggurat-core
This PR duplicates the linked readme structure recently created for algorand.
> chore: move detailed IPS/performance docs into separate readme

- .github/workflows/rippled.yml
- Upload only `latest-result` since `previous-result` is now stored by GCS.
- Supply secrets to `diff-with-previous` step.
> ci: only upload `latest-result`

- .github/workflows/build-rippled.yml
- .github/workflows/rippled.yml
- Implements runziggurat/ziggurat-core#52
- `rippled` is now built from the latest commit on `develop` instead of `master`.
> Grab node metadata
